name: Update blog posts list

on:
  push:
    branches:
      - main # 或者你的主分支名

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate blog post list
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # 指定你的文章源，这里是仓库内的文件夹
          feed_list: "./posts" 
          # 在 README.md 中寻找的标记名
          comment_tag_name: "BLOG-POST-LIST"
          # 生成列表的模板， $title 是文件名，$url 是文件路径
          template: "- [$title]($url)"
          # 日期格式
          date_format: "yyyy-mm-dd"
          # 列表条目前缀
          commit_message: "docs: update blog post list"
